version: "2"
services: 
  web:
    build: .
    image: qpair/flaskapp
    ports:
       - "5000:5000"
       - "8000:8000"
    volumes:
       - .:/code 
    mem_limit: 700m      
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
   
